import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Web3 Internet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Group 8665.png" />
      </Head>

      <header className='text-white text-sm mt-[100px] flex flex-col items-center justify-center   '>
<div>
<div>
          <h3 className='text-center'>WELCOME TO CRONOS</h3>
        </div>
        <div className='relative'>
        <Image src="/Icosahedron (1).png" width={180} height={350} alt="icon" className='overflow-hidden absolute -top-[30px] -left-[50px] z-1' ></Image>
          <h1 className='md:text-8xl text-center mt-[60px] z-5 text-5xl'>The Internet Of <br/>Blockchains.</h1>
          <p className="text-2xl mt-[30px] text-center ">Cronos is an ever expanding ecosystem connected<br/> apps and services,built  for a decentralized future</p>
        </div>
        <div className='absolute right-0 top-[350px] overflow-hidden'>
        <Image src="/Icosahedron.png" width={350} height={350} alt="icon" className='overflow-hidden' ></Image>
        </div>
</div>
       
      
      </header>

  <div className='mt-[300px]'>
    <div className=''>
      <h2 className='px-[60px] mb-[40px]'> COMMUNITY-OWNED AND OPERATED</h2>
      <div className='flex justify-between flex-col md:flex-row'>
      <div className='relative'>
      <Image src="/Helix.png" width={350} height={350} alt="icon" className=' z-5' ></Image>
      <div className='absolute top-[40px] md:left-[150px] md:w-[500px]  px-4 md:px-0'>
      <h1 className='md:text-6xl  md:w-[500px] leading-[70px] mb-[40px] text-5xl'>Enter a Universe <br/>of Connected Services</h1>
      <p className='md:w-[400px]'>Cronos apps and services connect using IBC, the inter-blockchain community protocol.This innovation enables you to freely exchange assets and data across sovereign</p>
      <div className='md:mt-[80px] mt-[50px]'>
      <Image src="/Frame 22.png" width={200} height={250} alt="icon" className=' z-5' ></Image>
      </div>
      </div>
      
      </div>

      <div className="mr-[200px] flex flex-col gap-[100px] mt-[150px] md:mt-0 px-3 md:px-0">
        <div>
          <h1 className='text-8xl'>265+</h1>
          <p>Apps $ Services</p>
        </div>

        <div>
          <h1 className='text-8xl'>$63B+</h1>
          <p>Digital Assets</p>
        </div>

      </div>
      </div>
    
    </div>
   
  </div>


  <div className='mt-[80px]'>
    <div className="flex flex-col items-center justify-center">
      <div className='relative px-4 md:px-0'>
      <Image src="/Thorus 3.png" width={600} height={750} alt="icon" className=' z-5' ></Image>

      <div className='absolute md:top-[160px] md:left-[50px] md:w-[500px] w-[300px] top-[30px] flex flex-col items-center justify-center   md:px-0'>
      <h3 className='text-center mb-[40px]'>ENTER THE CRONOS HUB</h3>
      <h1 className='text-5xl  md:w-[500px] leading-[50px] mb-[40px] text-center'>The Heart of the <br/>Interchain</h1>
      <p className='md:w-[500px] text-center text-sm ml-[50px] w-[350px]'>Cronos apps and services connect using IBC, the inter-blockchain community protocol.This innovation enables you to freely exchange assets and data across sovereign</p>
     
      </div>
      

      </div>

      <div className='grid grid-cols-1 md:grid-cols-2 gap-[40px] mt-[130px] md:mt-[30px]'>
        <div className='flex flex-col items-center justify-center'>
        <Image src="/Group 8663.png" width={300} height={750} alt="icon" className=' z-5' ></Image>
        <div className='md:w-[400px] md:ml-[70px] px-2'>
          <h2 className='text-3xl'>Security Provider</h2>
          <p>With the upcoming interchain security feature HEDRON will soon be securing many chains, in exchange for additional staking holds</p>
        </div>
        </div>

        <div className='flex flex-col items-center justify-center'>
        <Image src="/Group 8663.png" width={300} height={750} alt="icon" className=' z-5' ></Image>
        <div className='md:w-[400px] md:ml-[70px] px-2'>
          <h2 className='text-3xl'>Security Provider</h2>
          <p>With the upcoming interchain security feature HEDRON will soon be securing many chains, in exchange for additional staking holds</p>
        </div>
        </div>

        <div className='flex flex-col items-center justify-center'>
        <Image src="/Group 8665.png" width={300} height={750} alt="icon" className=' z-5' ></Image>
        <div className='md:w-[400px] md:ml-[70px] px-2'>
          <h2 className='text-3xl'>Security Provider</h2>
          <p>With the upcoming interchain security feature HEDRON will soon be securing many chains, in exchange for additional staking holds</p>
          <Image src="/Frame 22.png" width={200} height={250} alt="icon" className=' z-5 mt-[40px]' ></Image>
        </div>
        </div>

        <div className='flex flex-col items-center justify-center'>
        <Image src="/Group 8662.png" width={300} height={750} alt="icon" className=' z-5' ></Image>
        <div className='md:w-[400px] md:ml-[70px] px-2'>
          <h2 className='text-3xl'>Security Provider</h2>
          <p>With the upcoming interchain security feature HEDRON will soon be securing many chains, in exchange for additional staking holds</p>
        </div>
        </div>


      </div>
    </div>
  </div>

  <div className='mt-[80px] flex items-center justify-center'>
    <div className='flex items-center gap-[50px] flex-col md:flex-row'>
    <Image src="/Group 8683.png" width={600} height={750} alt="icon" className=' z-5' ></Image>
    <div>
      <h1 className='text-6xl leading-[70px] mb-[30px]'>Secured by <br/>the Hedoron</h1>
      <p className='md:w-[400px] px-2'>In return for securing services on the Cronos Hub, transactions fees and staking rewards are disturbed to HEDRON stalers</p>
     <div className='flex items-center gap-[40px] '>
     <Image src="/Frame 21.png" width={200} height={250} alt="icon" className=' z-5 mt-[40px]' ></Image> <p>Learn more</p>
     </div>
     
    </div>
    </div>
  </div>

<div className='mt-[80px] flex items-center justify-center'>

  <div>
    <div>
      <h1 className='text-5xl mb-[40px]'>Be Part Of The Open <br/>Economy Of The Future.</h1>
    </div>

    <div>
      <h2 className="text-2xl mb-[40px]">Powerful Features</h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-[30px]">
        <div className='h-[600px] bg-[#141414] w-[500px] p-4'>
          <h3 className="mt-[30px]">INTERCHAIN ACCOUNTS</h3>
          <div className="relative ">
          <Image src="/locker-dynamic-premium.png" width={250} height={200} alt="icon" className='z-5'></Image>
          <Image src="/Ellipse 81.png" width={250} height={200} alt="icon" className='z-1 absolute top-0 -left-[50px] bottom-0'></Image>
          </div>

         

          <h1 className="text-5xl mt-[20px]">One secure account for all digital assets.</h1>

          <h3 className="mt-[80px]">COMING SOON</h3>
        </div>

        <div className='h-[600px]  '>

          <div className='h-[300px]  w-[400px] bg-[#141414] flex p-4'>
            <div>
            <h3 className="mt-[10px]">INTERCHAIN ACCOUNTS</h3>
            <h1 className="text-4xl mt-[30px]">Swap tokens & collectibles.</h1>

<h3 className="mt-[40px]">COMING SOON</h3>
            </div>
            <Image src="/Group 8662.png" width={150} height={100} alt="icon"></Image>
          </div>

          <div className='h-[300px]  w-[400px] flex gap-[20px] mt-[10px] '>

            <div className='h-[300px]  w-[200px] bg-[#141414] p-3'>
            <h3 className="mt-[10px]">LIQUIDITY POOL</h3>
            <h1 className="text-4xl mt-[20px]">Provide liquidty,<br/>earn rewards.</h1>

                 <h3 className="mt-[30px]">COMING SOON</h3>
            </div>

            <div  className='h-[300px]  w-[200px] bg-[#141414] p-3'>
            <h3 className="mt-[10px]">WRAPPED ETH</h3>
            <h1 className="text-4xl mt-[20px]">Eth<br/>included.</h1>

                 <h3 className="mt-[11 0px]">COMING SOON</h3>
            </div>

          </div>

        </div>

      </div>

    </div>

  </div>



</div>


  <div className='mt-[80px] '>
    <div className='flex justify-between flex-col md:flex-row'>
      <div className='md:ml-[200px]'>
        <h3>TECHNOLOGY</h3>
        <div className='w-[600px] px-3'>
        <h1 className='md:text-6xl leading-[70px] text-4xl'>The most trusted<br/> way to build<br/> value</h1>
        <div>
          <p className='mt-[40px] md:w-[400px] w-[300px]'>Cronos is a state-of-the-art-of-blockchain framework that powers the Cronos Hub and its rapidly expanding bit of sovereign</p>
          <p className='mt-[40px] md:w-[400px] w-[300px]'>Developers can use the SDK to build innovative applications that create value through exchange with Cronos hub</p>
        </div>
        <div className='mt-[80px]'>
          <h4>LOW FEES</h4>
          <div>
            <h1 className='text-7xl'>$0.01</h1>
            <p>Enjoy the lowest fees - almost zero</p>
          </div>
        </div>
        </div>

      </div>
      <div className='relative h-[300]'>
      <Image src="/Cylinder 5.png" width={480} height={300} alt="icon" className=' z-5 mt-[40px]' ></Image>
      <div className='absolute top-[100px] left-[100px]'>
        <h3>PROOF OF STAKE</h3>
        <div>
        <h1 className='text-9xl mt-[30px] mb-[30px]'>99%</h1>
        <p>Low carbon footprint</p>
        </div>
      
      </div>
      <div className='absolute bottom-[10px] left-[50px]'>
        <h3>FAST TRANSACTIONS</h3>
        <div>
        <h1 className='text-9xl mt-[30px] mb-[30px]'>5 sec</h1>
        <p>Transactions confirmed in seconds</p>
        </div>
      
      </div>
      </div>
    </div>
  </div>

<div className='mt-[80px] flex items-center justify-center '>
  <div className="flex flex-col items-center justify-center">
    <h1 className='text-5xl mt-[30px] mb-[30px] text-center'>
      Join the network.
    </h1>


    <div className="grid grid-cols-1 md:grid-cols-3 gap-[30px]">
        <div className='bg-[#141414] h-[350px] w-[300px] p-4 relative'>
          <h3 className='text-sm'>CONNECT</h3>

          <div className="mt-[50px] flex flex-col items-center justify-center">
            <h2 className='font-bold text-2xl text-center mb-[20px]'>Connect Chains</h2>
            <p className='text-sm'>Grow the economy of your chain by connecting to Cronos Hub services using IBT protocol</p>
          </div>
          <Image src="/copy-success.png" width={20} height={20} alt="icon" className='absolute left-[20px] bottom-[20px]'></Image>
        </div>

        <div className='bg-[#141414] h-[350px] w-[300px] p-4 relative'>
          <h3 className='text-sm'>CONNECT</h3>

          <div className="mt-[50px] flex flex-col items-center justify-center">
            <h2 className='font-bold text-2xl text-center mb-[20px]'>Connect Chains</h2>
            <p className='text-sm'>Grow the economy of your chain by connecting to Cronos Hub services using IBT protocol</p>
          </div>
          <div>
            <Image src="/copy-success.png" width={20} height={20} alt="icon" className='absolute left-[20px] bottom-[20px]'></Image>
          </div>

        </div>

        <div className='bg-[#141414] h-[350px] w-[300px] p-4 relative'>
          <h3 className='text-sm'>CONNECT</h3>

          <div className="mt-[50px] flex flex-col items-center justify-center">
            <h2 className='font-bold text-2xl text-center mb-[20px]'>Connect Chains</h2>
            <p className='text-sm'>Grow the economy of your chain by connecting to Cronos Hub services using IBT protocol</p>
          </div>
          <Image src="/copy-success.png" width={20} height={20} alt="icon" className='absolute left-[20px] bottom-[20px]'></Image>

        </div>
    </div>
  </div>
</div>
    <div className='mt-[100px] '>

      <div className="flex justify-between flex-col md:flex-row">
        <div className='relative'>
        <Image src="/Sphere.png" width={350} height={750} alt="icon" className=' z-5' ></Image>
        <div className='absolute top-[50px] md:left-[140px] px-3'>
          <h1 className="text-5xl leading-[60px] mb-[40px]">Meet the worldwide community.</h1>
          <p>Join the fast-growing community of developers and innovators connected all over the world building the new era of the interest</p>
          <div className="mt-[50px] text-2xl font-bold flex gap-[15px]">
            Community {`>>>`}
         
          </div>
        </div>
        </div>
      

      <div className="md:mr-[200px] w-[350px] flex flex-col gap-[100px] px-3">
        <div>
          <h3 className="font-bold text-2xl mb-[15px]">Community Chat {`>>>`}</h3>
          <p className="text-sm">Ask general questions and chat with the worldwide community on telegram</p>
        </div>

        <div>
          <h3 className="font-bold text-2xl mb-[15px]">Twitter {`>>>`}</h3>
          <p className="text-sm">Ask general questions and chat with the worldwide community on telegram</p>
        </div>


        <div>
          <h3 className="font-bold text-2xl mb-[15px]">Developer Chat {`>>>`}</h3>
          <p className="text-sm">Ask general questions and chat with the worldwide community on telegram</p>
        </div>


        <div>
          <h3 className="font-bold text-2xl mb-[15px]">Cronos forum {`>>>`}</h3>
          <p className="text-sm">Ask general questions and chat with the worldwide community on telegram</p>
        </div>



      </div>




      </div>





    </div>


<div className="mt-[150px] flex items-center justify-center">
  <div className="flex gap-[50px] flex-col md:flex-row">
    <div>
      <h1 className="font-bold text-2xl">Receive Transmissions</h1>
      <p>Unsubscribe at anytime. Privacy policy {`>>>`}</p>
    </div>
    <div>
      <input type="email" placeholder="your email" className='bg-[#141414] text-white p-2 py-3 w-[300px]'/>
    </div>
  </div>
</div>

<div className="mt-[100px]">
  <hr/>
</div>
    </>
  )
}
